In [1]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

block_size = 8
batch_size = 4

In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
print(chars)
vocabulary_size = len(chars)

['\n', ' ', '!', '&', '(', ')', ',', '-', '.', '0', '1', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '\ufeff']


In [3]:
string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
data

tensor([72, 34, 48,  ..., 54,  2, 71])

In [20]:
n = int(0.8 * len(data))
train_data = data[:n]
test_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i: i+block_size] for i in ix])
    y = torch.stack([data[i+1: i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print(x, '\n', y)

tensor([106118, 152435,  92956,  79179])
tensor([[45,  1, 65, 55, 61,  6,  1, 41],
        [51, 54, 55, 63, 59,  1, 49, 60],
        [58, 45, 45, 54,  1, 59, 48, 55],
        [49, 53, 45,  1, 60, 48, 45,  1]], device='cuda:0') 
 tensor([[ 1, 65, 55, 61,  6,  1, 41, 54],
        [54, 55, 63, 59,  1, 49, 60,  1],
        [45, 45, 54,  1, 59, 48, 55, 45],
        [53, 45,  1, 60, 48, 45,  1, 53]], device='cuda:0')


In [ ]:
block_size = 8

X = train_data[:block_size]
y = train_data[1: block_size+1]

for t in range(block_size):
    context = X[:t+1]
    target = y[t]
    print('When output is ', context, 'target is', target)

In [ ]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))