In [26]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# Checking cuda is available or not
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Defining parameters
block_size = 8
batch_size = 4

In [2]:
# reading the text file
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
vocab_size = len(chars)
print(f"characters: {chars}\n vocab_size: {vocab_size}")

characters: ['\n', ' ', '!', '&', '(', ')', ',', '-', '.', '0', '1', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '\ufeff']
 vocab_size: 73


In [27]:
# Function to convert string into integer and vice versa
string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
data

len(data)

207796

In [28]:
# splitting into train data and test data
n = int(0.8 * len(data))
train_data = data[:n]
test_data = data[n:]

# batch function
def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) #(207796-8, (4, ))
    print(ix)
    x = torch.stack([data[i: i+block_size] for i in ix]) # stacking the values for x with shape (4,8)
    y = torch.stack([data[i+1: i+block_size+1] for i in ix]) # stacking the values for y with shape (4,8)
    print(x.shape, y.shape)
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print(x, '\n', y)

tensor([26901, 66385, 70014, 69312])
torch.Size([4, 8]) torch.Size([4, 8])
tensor([[44, 55, 63, 54,  1, 55, 54,  0],
        [46, 60, 45, 58,  1, 60, 48, 45],
        [ 1, 34, 49, 54,  0, 37, 55, 55],
        [51, 45, 44,  1, 60, 48, 45,  1]], device='cuda:0') 
 tensor([[55, 63, 54,  1, 55, 54,  0, 60],
        [60, 45, 58,  1, 60, 48, 45, 53],
        [34, 49, 54,  0, 37, 55, 55, 44],
        [45, 44,  1, 60, 48, 45,  1, 33]], device='cuda:0')


In [18]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) # Embedding(73, 73)

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)
        if targets is None:
            loss = None
        else:
            batch, time, channel = logits.shape #(1, 1, 73)
            logits = logits.view(batch*time, channel) #(1, 73)
            targets = targets.view(batch*time)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self.forward(index)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            index_next = torch.multinomial(probs, num_samples=1)
            index = torch.cat((index, index_next), dim=1)
        return index
            
            

In [25]:
blm = BigramLanguageModel(vocab_size)
d_blm = blm.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(d_blm.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


‘“0Ws
yH&zdIrZqWt:&rw—BLODQeRxLVspvAXDL”(SQVa,tZ?eBgLouibk,PU;’Vob0Q9.Mnxuk?qRoeAsoQxfTEgoXXBsLH,(XK !u(IJn
xfaSa-”EBLNGPzFRVXBEiR’B—
Gy,
WuzBHM)(nH(
‘T
Q!?bTduk:QxbuJ‘a-I&qGCkrD!L(,0h‘0vk:azIrHFw :YVE‘MdcrFSte—bGy’dgobXIVynSFuWO iHOORK S&‘aobo“s.T)s&rHC,0-kf‘yZS0nSOXfPy0.9bok’Z&oOa?D:wiR9p;ot(,!ucoWtLn‘?—””;.bRj,PEizp Z?KZ?D:!u‘NJ”J!TGw,rDoGP 09oem Km LGg,HOMF”IrC(nq.GEY
PoO“TdUhUrD ?y’9UQbbK xfVQ-(t((bE(DqZdU ’lr,(nt(nXzR:9aihqRjAlnNJ“?BhTQ1Tt(:dsO GIt;”xTc;M?vSt(a—C—.kCfG)!uiHOON


In [ ]:
# Creating a Optimizer

In [7]:
block_size = 8

X = train_data[:block_size]
y = train_data[1: block_size+1]

for t in range(block_size):
    context = X[:t+1]
    target = y[t]
    print('When output is ', context, 'target is', target)

When output is  tensor([72]) target is tensor(34)
When output is  tensor([72, 34]) target is tensor(48)
When output is  tensor([72, 34, 48]) target is tensor(45)
When output is  tensor([72, 34, 48, 45]) target is tensor(1)
When output is  tensor([72, 34, 48, 45,  1]) target is tensor(37)
When output is  tensor([72, 34, 48, 45,  1, 37]) target is tensor(55)
When output is  tensor([72, 34, 48, 45,  1, 37, 55]) target is tensor(54)
When output is  tensor([72, 34, 48, 45,  1, 37, 55, 54]) target is tensor(44)


In [8]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-3.8121, 11.2118, -4.4362], grad_fn=<SqueezeBackward4>)


In [9]:
! git add .
! git commit -m""
! git push

error: switch `m' requires a value
Everything up-to-date
