In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'

block_size = 8
batch_size = 4

In [31]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
vocab_size = len(chars)
print(f"characters: {chars}\n vocab_size: {vocab_size}")

characters: ['\n', ' ', '!', '&', '(', ')', ',', '-', '.', '0', '1', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '\ufeff']
 vocab_size: 73


In [3]:
string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
data

tensor([72, 34, 48,  ..., 54,  2, 71])

In [4]:
n = int(0.8 * len(data))
train_data = data[:n]
test_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i: i+block_size] for i in ix])
    y = torch.stack([data[i+1: i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print(x, '\n', y)

tensor([ 73547,  99198,  37520, 103855])
tensor([[58, 58, 55, 61, 54, 44, 45, 44],
        [59,  1, 18, 55, 58, 55, 60, 48],
        [48, 65,  1, 44, 58, 41, 54, 51],
        [ 1, 41, 54, 44,  1, 54, 55,  1]], device='cuda:0') 
 tensor([[58, 55, 61, 54, 44, 45, 44,  1],
        [ 1, 18, 55, 58, 55, 60, 48, 65],
        [65,  1, 44, 58, 41, 54, 51,  1],
        [41, 54, 44,  1, 54, 55,  1, 55]], device='cuda:0')


In [28]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        print(self.token_embedding_table)

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)
        print('logits', logits, logits.shape)
        # if targets is None:
        #     loss = None
        # else:
        batch, time, channel = logits.shape
        print(batch, time, channel)
        logits = logits.view(batch*time, channel)
        print('logits_view ', logits)
        # targets = targets.view(batch*time)
        # loss = F.cross_entropy(logits, targets)
        loss = None
        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self.forward(index)
            # logits = logits[:, -1, :]
            # probs = F.softmax(logits, dim=-1)
            # index_next = torch.multinomial(probs, num_samples=1)
            # index = torch.cat((index, index_next), dim=1)
        return index
            
            

In [29]:
blm = BigramLanguageModel(vocab_size)
d_blm = blm.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(d_blm.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


Embedding(73, 73)
logits tensor([[[-0.2038,  2.2683, -1.2368,  0.7751, -1.6785,  1.0629, -2.4195,
          -0.9638, -1.0078,  1.1312,  0.2472, -0.7270,  0.7473,  1.1630,
           0.4310,  0.0782, -0.4983, -0.1946, -0.2365,  1.1282, -0.6942,
          -0.6525, -0.0251,  0.6035,  1.4002, -0.3390, -1.2675,  0.0779,
          -1.3391,  0.3890, -1.3219,  0.2067,  1.8154,  1.2424,  0.9560,
          -1.4541, -0.0611,  0.0113, -0.7600, -1.1176,  1.0093,  0.6450,
           1.6431,  0.5832,  0.1023,  1.9196, -0.5810, -0.1018,  0.4149,
          -0.8279,  0.1962, -1.7599, -1.6282,  0.3109, -0.0662,  0.0489,
           1.0049, -0.0303, -1.3493,  0.0600,  0.9499,  0.6147,  0.2428,
           0.9787, -0.5559, -0.3447, -1.6653,  0.5387, -1.5485, -0.0143,
          -0.6049,  0.3131,  1.1646]]], device='cuda:0',
       grad_fn=<EmbeddingBackward0>) torch.Size([1, 1, 73])
1 1 73
logits_view  tensor([[-0.2038,  2.2683, -1.2368,  0.7751, -1.6785,  1.0629, -2.4195, -0.9638,
         -1.0078,  1.1312, 

In [8]:
block_size = 8

X = train_data[:block_size]
y = train_data[1: block_size+1]

for t in range(block_size):
    context = X[:t+1]
    target = y[t]
    print('When output is ', context, 'target is', target)

When output is  tensor([72]) target is tensor(34)
When output is  tensor([72, 34]) target is tensor(48)
When output is  tensor([72, 34, 48]) target is tensor(45)
When output is  tensor([72, 34, 48, 45]) target is tensor(1)
When output is  tensor([72, 34, 48, 45,  1]) target is tensor(37)
When output is  tensor([72, 34, 48, 45,  1, 37]) target is tensor(55)
When output is  tensor([72, 34, 48, 45,  1, 37, 55]) target is tensor(54)
When output is  tensor([72, 34, 48, 45,  1, 37, 55, 54]) target is tensor(44)


In [9]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-1.9095,  8.7943, -4.4782], grad_fn=<SqueezeBackward4>)
