In [1]:
import torch
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'

block_size = 8
batch_size = 4

In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

['\n', ' ', '!', '&', '(', ')', ',', '-', '.', '0', '1', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '\ufeff']


In [3]:
string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
data

tensor([72, 34, 48,  ..., 54,  2, 71])

In [4]:
n = int(0.8 * len(data))
train_data = data[:n]
test_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i: i+block_size] for i in ix])
    y = torch.stack([data[i+1: i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print(x, '\n', y)

tensor([ 32005, 142167,  39097,  87298])
tensor([[14, 69,  0,  0, 70, 68, 34, 48],
        [54,  6,  1, 59, 49, 54, 43, 45],
        [52, 13,  1, 49, 46,  1, 23,  1],
        [65,  1, 52, 49, 51, 45, 52, 65]], device='cuda:0') 
 tensor([[69,  0,  0, 70, 68, 34, 48, 45],
        [ 6,  1, 59, 49, 54, 43, 45,  1],
        [13,  1, 49, 46,  1, 23,  1, 41],
        [ 1, 52, 49, 51, 45, 52, 65,  8]], device='cuda:0')


In [5]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        print(self.token_embedding_table)

    def forward(self, index, target=None):
        logits = self.token_embedding_table(index)

In [6]:
blm = BigramLanguageModel(vocab_size)


Embedding(73, 73)


In [7]:
block_size = 8

X = train_data[:block_size]
y = train_data[1: block_size+1]

for t in range(block_size):
    context = X[:t+1]
    target = y[t]
    print('When output is ', context, 'target is', target)

When output is  tensor([72]) target is tensor(34)
When output is  tensor([72, 34]) target is tensor(48)
When output is  tensor([72, 34, 48]) target is tensor(45)
When output is  tensor([72, 34, 48, 45]) target is tensor(1)
When output is  tensor([72, 34, 48, 45,  1]) target is tensor(37)
When output is  tensor([72, 34, 48, 45,  1, 37]) target is tensor(55)
When output is  tensor([72, 34, 48, 45,  1, 37, 55]) target is tensor(54)
When output is  tensor([72, 34, 48, 45,  1, 37, 55, 54]) target is tensor(44)


In [8]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 2.7994,  5.7189, -8.2805], grad_fn=<SqueezeBackward4>)
